#Extension file

- universal extension for python .py(this can run anywhere)
- jupyter notebook .ipynb - interactive python notebook (this can run only jupyter notebok)

In [1]:
pwd

'C:\\Users\\91955\\python files'

In [1]:
import keyword
print(keyword.kwlist)

['False', 'None', 'True', '__peg_parser__', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


In [5]:
a=20

In [6]:
10/2


5.0

In [7]:
10//2

5

In [8]:
15/2

7.5

In [9]:
15//2

7

In [10]:
a= 'learnbay'
b= 'learnbaa'
print(a>b)

True


In [16]:
print (chr(97))
print(ord('a'))

a
97


In [19]:
x= 24
y = 16

print (x & y)

16


In [ ]:
1 1 0 0 0 
1 0 0 0 0
1 0 0 0 0

In [18]:
bin(24)

'0b11000'

In [20]:
bin(16)

'0b10000'

In [21]:
10%2

0

In [2]:
x= 200
y= 200

print(id(x))
print(id(y))

1564776489616
1564776489616


In [4]:
x= 257
y= 257

print(id(x))
print(id(y))

1564857822736
1564857823088


In [6]:
a = input('ask me')
print(type(a))

ask me10
<class 'str'>


In [7]:
a = int(input('ask me'))
print(type(a))

ask me10
<class 'int'>


In [10]:
a = eval(input('ask me'))
print(type(a))

ask me10.4
<class 'float'>


In [11]:
a= 10
float(a)

10.0

In [12]:
a=10
b= 20
c=30

print(a , end = '')
print(b, end = '')
print(c , end = '')

102030

In [13]:
a= input("enter the first name")
b= input("enter the last name")
print (a,b)

enter the first nameNeelam
enter the last nameMehra
Neelam Mehra


In [16]:
a= input("enter the first name")
b= input("enter the last name")
print (f " {a} My first name  and {b} is my last name")

SyntaxError: invalid syntax (Temp/ipykernel_11980/3363930894.py, line 3)

In [17]:
a= input("enter the first name")
b= input("enter the last name")
print (" {} My first name  and {} is my last name".format(a,b))

enter the first nameNeelam
enter the last nameMehra
 Neelam My first name  and Mehra is my last name


In [18]:
a= 10
bool(a)

True

In [1]:
a= 'Python'

a[-3:0:1]

''

 p  y  t  h  o  n
 0  1  2  3  4  5
-6 -5 -4 -3 -2 -1

In [2]:
a[-2::-1]

'ohtyP'

In [3]:
a[6:3:2]

''

In [4]:
a[6:1:-2]

'nh'

In [6]:
a= 'Neelam'
b = 'Mehra'
print (a +" "+b)   #concatination

Neelam Mehra


In [7]:
print(dir(str))

['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mod__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmod__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'capitalize', 'casefold', 'center', 'count', 'encode', 'endswith', 'expandtabs', 'find', 'format', 'format_map', 'index', 'isalnum', 'isalpha', 'isascii', 'isdecimal', 'isdigit', 'isidentifier', 'islower', 'isnumeric', 'isprintable', 'isspace', 'istitle', 'isupper', 'join', 'ljust', 'lower', 'lstrip', 'maketrans', 'partition', 'removeprefix', 'removesuffix', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'strip', 'swapcase', 'title', 'translate', 'upper', 'zfill']


In [12]:
s= 'this is a python class'
s1= 'THIS IS a Python Class'


print(s.capitalize())
print(s1.capitalize())
print ('_____'*25)

print(s.lower())
print(s1.lower())
print ('_____'*25)


print(s.upper())
print(s1.upper())
print ('_____'*25)


print(s.swapcase())
print(s1.swapcase())
print ('_____'*25)

print(s.title())
print(s1.title())
print ('_____'*25)

print(s.isupper())


This is a python class
This is a python class
_____________________________________________________________________________________________________________________________
this is a python class
this is a python class
_____________________________________________________________________________________________________________________________
THIS IS A PYTHON CLASS
THIS IS A PYTHON CLASS
_____________________________________________________________________________________________________________________________
THIS IS A PYTHON CLASS
this is A pYTHON cLASS
_____________________________________________________________________________________________________________________________
This Is A Python Class
This Is A Python Class
_____________________________________________________________________________________________________________________________
False


In [14]:
##special char/escaping char


In [15]:
##\n

print('hello\nworld')

hello
world


In [17]:
#\

print('this is python\'s class')

this is python's class


In [17]:
d= [[1,2,4],[5,6,7],[8,[9,10,['a','b']]]]

In [22]:
d[-1][-1][-1][-2]

'a'

In [23]:
d[2][-1][-1][-2]

'a'

In [24]:
d[2][1][2][0]

'a'

In [9]:
b= [1,2,3,['afsan','khan'],['learmbay']]


In [10]:
b[-2]

['afsan', 'khan']

In [12]:
b[-2][-1]

'khan'

In [13]:
b[-2][-1][::2]

'ka'

In [27]:
dir(list)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [42]:
af= [1,2,3,4]
bf=af
print(af)
print(bf)
print(id(af))
print(id(af))
print("---"*25)

bf[1]=100
print(af)
print(bf)
print(id(af))
print(id(af))


[1, 2, 3, 4]
[1, 2, 3, 4]
2472529943168
2472529943168
---------------------------------------------------------------------------
[1, 100, 3, 4]
[1, 100, 3, 4]
2472529943168
2472529943168


In [43]:
cf= [1,2,3,4]
df= cf.copy()
print(cf)
print(df)
print(id(cf))
print(id(df))
print('----'*24)

df[1]=100
print(cf)
print(df)
print(id(cf))
print(id(df))

[1, 2, 3, 4]
[1, 2, 3, 4]
2472529942912
2472529905280
------------------------------------------------------------------------------------------------
[1, 2, 3, 4]
[1, 100, 3, 4]
2472529942912
2472529905280


In [45]:
for i in ['afsan', 'sakshi','mohit']:
    print(i)

afsan
sakshi
mohit


In [1]:
import numpy as np

In [4]:
arr = np.array([10, 15, 20, 25, 30, 35, 40])

print(arr[::2])

[10 20 30 40]


In [5]:
arr = np.array([10, 15, 20, 25, 30, 35, 40])

print(arr[1:4:2])

[15 25]


In [6]:
#iteration in numpy


arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)


1
2
3
4
5
6


In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [8]:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [9]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [10]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [11]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [12]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [13]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [1]:
pwd

'C:\\Users\\91955\\python files'